USE [BatchProcessorExample]
GO

/****** Object:  Table [dbo].[mapping]    Script Date: 7/15/2020 9:02:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[mapping](
	[MPG_PK] [int] NOT NULL,
	[NME] [varchar](100) NULL,
	[AGE] [int] NULL,
	[GRD] [varchar](6) NULL,
PRIMARY KEY CLUSTERED 
(
	[MPG_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


