USE [master]
GO

/****** Object:  Database [BatchProcessorExample]    Script Date: 7/15/2020 8:02:15 PM ******/
CREATE DATABASE [BatchProcessorExample]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BatchProcessorExample', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BatchProcessorExample.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BatchProcessorExample_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BatchProcessorExample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BatchProcessorExample].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BatchProcessorExample] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET ARITHABORT OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BatchProcessorExample] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BatchProcessorExample] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BatchProcessorExample] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BatchProcessorExample] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET RECOVERY FULL 
GO

ALTER DATABASE [BatchProcessorExample] SET  MULTI_USER 
GO

ALTER DATABASE [BatchProcessorExample] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BatchProcessorExample] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BatchProcessorExample] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BatchProcessorExample] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BatchProcessorExample] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BatchProcessorExample] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BatchProcessorExample] SET  READ_WRITE 
GO


